<a href="https://colab.research.google.com/github/amna-ejaz16/python-data-science-fundamentals/blob/main/Numpy_Hands_On_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Performance and Memory Usage Comparison





In [ ]:
# Execution Performance
import numpy as np
import time
import sys

In [ ]:
# python_list
size=50
py_list = list(range(size))
start_time = time.time()
sq_list = [x**2 for x in py_list]
end_time = time.time()
print(f"Python list time is {end_time - start_time} seconds")

# numPy array
numpy_array = np.array(py_list)
start_time = time.time()
sq_array = numpy_array**2
end_time = time.time()
print(f"NumPy Array time is {end_time-start_time} seconds")

# Memory
print(f"Python list memory = {sys.getsizeof(py_list)*len(py_list)} in bytes")
print(f"NumPy array memory = {numpy_array.nbytes} in bytes")


Python list time is 0.00018715858459472656 seconds
NumPy Array time is 8.153915405273438e-05 seconds
Python list memory = 22800 in bytes
NumPy array memory = 400 in bytes


# Creating Arrays from List

In [ ]:
import numpy as np
# 1D Arrays
arr = np.array([1,2,3,4,8.0])
print(arr, type(arr), arr.shape, arr.ndim, arr.dtype)

arr1 = np.array(["amna", "ejaz", 64, 16])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.dtype)
print(arr1.ndim)


# 2D Arrays
arr2D = np.array([['a','b','c'], ['d','e','f']])
print(arr2D.ndim)
print(arr2D.shape)

[1. 2. 3. 4. 8.] <class 'numpy.ndarray'> (5,) 1 float64
['amna' 'ejaz' '64' '16']
<class 'numpy.ndarray'>
(4,)
<U21
1
2
(2, 3)


# Creating Arrays using Built-in Methods

In [ ]:
arr1 = np.zeros((3,3), dtype="int16")
print(arr1)
print(type(arr1))
print(arr1.ndim)

arr2 = np.ones((3,4), dtype="int16")
print(arr2)
print(arr2.shape)

arr3 = np.full((4,5), 66)
print(arr3)

arr4 = np.eye((3), dtype="int16")
print(arr4)

arr5 = np.arange(1,10,2)
print(arr5)

arr6 = np.linspace(1,100,6, dtype="int16")
print(arr6)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
2
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(3, 4)
[[66 66 66 66 66]
 [66 66 66 66 66]
 [66 66 66 66 66]
 [66 66 66 66 66]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[1 3 5 7 9]
[  1  20  40  60  80 100]


# Array Properties

In [ ]:
arr = np.array([[1,3,5],[7,9,11]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(type(arr))

# Type Casting
my_arr = np.array([11,12,13,14], dtype="float32")
print(my_arr)

int_array = my_arr.astype(np.int16)
print(int_array)

[[ 1  3  5]
 [ 7  9 11]]
(2, 3)
2
<class 'numpy.ndarray'>
[11. 12. 13. 14.]
[11 12 13 14]


# Array Operations

In [ ]:
# Reshaping Arrays
arr = np.array([[10,20,30], [60,70,90]])
reshaped = arr.reshape((3,2))
print(reshaped)

flattened = arr.flatten()
print(flattened)


# Indexing
# Fancy Indexing
arr = np.array([8,9,10,11])
idx = [1,2,3]
print(arr[idx])

# Boolean Indexing
arr = np.array([22,34,54,99])
print(arr[arr>22])
print(arr[arr%2==0])
print(arr[arr%2!=0])



[[10 20]
 [30 60]
 [70 90]]
[10 20 30 60 70 90]
[ 9 10 11]
[34 54 99]
[22 34 54]
[99]


In [ ]:
# Slicing
arr = np.array([5,8,9,10])
print(arr[:])
print(arr[1:3])
print(arr[2:])
print(arr[:2])
print(arr[::2])


# Copy_vs_View_in_Slice
numbers = [1,2,3,4,5]
sub_list = numbers[1:3]
print(sub_list)

sub_list[0] = 100
print(sub_list)
print(numbers)


arr = np.array([1,2,3,4,5])
sub_array = arr[1:3]
print(sub_array)

sub_array[0] = 50
print(sub_array)
print(arr)


[ 5  8  9 10]
[8 9]
[ 9 10]
[5 8]
[5 9]
[2, 3]
[100, 3]
[1, 2, 3, 4, 5]
[2 3]
[50  3]
[ 1 50  3  4  5]


# Multi-dimentional Arrays

In [ ]:
import numpy as np

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D,axis=0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D,axis=1)
print(sum_of_rows)

print(arr2D[1:2,1:2])
print(arr2D[1:,2])
print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[5]]
[6 9]
[[2]
 [5]]


# 3D Arrays

In [ ]:
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D)
print(arr3D.shape)
print(arr3D.ndim)

# Slicing
print(arr3D[:,0,:])
print(arr3D[:,:,1])
arr3D[:,0,:] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3
[[1 2]
 [7 8]]
[[ 2  4  6]
 [ 8 10 12]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


# Broadcasting

In [ ]:
arr1 =np.array([1,2,3,4,5])
print(arr1+5)

arr2 = np.array([1,2,3,4,5])
arr3 = np.array([1,1,1,1,1])
print(arr2 + arr3)

[ 6  7  8  9 10]
[2 3 4 5 6]


In [ ]:
import numpy as np

A = np.array([[100],[200]])

B = np.array([1, 2, 3])

C = A + B
print(C)

[[101 102 103]
 [201 202 203]]


In [ ]:
arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)
print(mean)
print(std_dev)

normalized_array = (arr-mean)/std_dev
print(normalized_array)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


# Mathematical Functions

In [ ]:
my_array = np.array([1,2,3,4,5])
print(np.sum(my_array))
print(np.prod(my_array))
print(np.min(my_array))
print(np.max(my_array))
print(np.argmin(my_array))
print(np.argmax(my_array))
print(np.mean(my_array))
print(np.std(my_array))
print(np.median(my_array))
print(np.var(my_array))

C = np.array([10,20,30,40,50])
D = np.array([1,2,3,4,5])
print(np.divide(C,D))

E = np.array([100,100])
F = np.array([99,98])
print(np.subtract(E,F))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0
[10. 10. 10. 10. 10.]
[1 2]


# Power Functions

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow((arr),2))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]


# Log Functions

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


# Rounding Functions

In [ ]:
arr = np.array([1.5,2.8,3.6,4.1,5.2])
print(np.round(arr))
print(np.ceil(arr))
print(np.floor(arr))
print(np.trunc(arr))

[2. 3. 4. 4. 5.]
[2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


# Miscellaneous Functions

In [ ]:
arr = np.array([1,-6,6,4,5])
print(np.unique(arr))
print(np.abs(arr))
print(np.sort(arr))

[-6  1  4  5  6]
[1 6 6 4 5]
[-6  1  4  5  6]
